### ISSUE TITLE
Error with `await import` and the following statement on the same line

### ISSUE THREAD

**Issue by pabloalmunia** [node-projects/esprima-next#38]
When a `await import()` is in the same line with the next sentence, an error is throw `Unexpected identifier`.

### Steps to reproduce

This code work perfectly:

```js
esprima.parseModule(`
async function load (i) {
  let c = await import(i); 
  console.log(c);
}`);
```

But this other code throw an error:

```js
esprima.parseModule(`
async function load (i) {
  let c = await import(i);  console.log(c);
}`);
```

The error message is:

```
    throw this.unexpectedTokenError(token, message);
    ^
Error: Line 3: Unexpected identifier
    at ErrorHandler.constructError (C:\Users\pablo\Documents\Dropbox\WebstormProjects\graphane\graphane\node_modules\esprima-next\dist\esprima.cjs:1477:17)
    at ErrorHandler.createError (C:\Users\pablo\Documents\Dropbox\WebstormProjects\graphane\graphane\node_modules\esprima-next\dist\esprima.cjs:1490:25)
    at Parser.unexpectedTokenError (C:\Users\pablo\Documents\Dropbox\WebstormProjects\graphane\graphane\node_modules\esprima-next\dist\esprima.cjs:2885:32)
    at Parser.throwUnexpectedToken (C:\Users\pablo\Documents\Dropbox\WebstormProjects\graphane\graphane\node_modules\esprima-next\dist\esprima.cjs:2894:16)
    at Parser.consumeSemicolon (C:\Users\pablo\Documents\Dropbox\WebstormProjects\graphane\graphane\node_modules\esprima-next\dist\esprima.cjs:3179:14)
    at Parser.parseLexicalDeclaration (C:\Users\pablo\Documents\Dropbox\WebstormProjects\graphane\graphane\node_modules\esprima-next\dist\esprima.cjs:4469:10)
    at Parser.parseStatementListItem (C:\Users\pablo\Documents\Dropbox\WebstormProjects\graphane\graphane\node_modules\esprima-next\dist\esprima.cjs:4399:58)
    at Parser.parseFunctionSourceElements (C:\Users\pablo\Documents\Dropbox\WebstormProjects\graphane\graphane\node_modules\esprima-next\dist\esprima.cjs:5218:22)
    at Parser.parseFunctionDeclaration (C:\Users\pablo\Documents\Dropbox\WebstormProjects\graphane\graphane\node_modules\esprima-next\dist\esprima.cjs:5371:23)
    at Parser.parseStatement (C:\Users\pablo\Documents\Dropbox\WebstormProjects\graphane\graphane\node_modules\esprima-next\dist\esprima.cjs:5145:54) {
  index: 92,
  lineNumber: 3,
  description: 'Unexpected identifier'
}
```

**Comment by jogibear9988** [comment]
fixed. :-)

**Comment by pabloalmunia** [comment]
Great job...
